/**
 * Generates src/commands/_all.ts with static imports for all command files.
 * This is needed because Bun's compiled binaries can't do runtime glob/dynamic imports.
 * Run automatically as part of the build step.
 */
import { Glob } from "bun";

const glob = new Glob("*.tsx");
const commands: string[] = [];

for (const file of glob.scanSync({
  cwd: `${import.meta.dir}/../src/commands`,
})) {
  if (file !== "index.tsx") {
    const name = file.replace(/\.tsx$/, "");
    commands.push(name);
  }
}

commands.sort();

const content = [
  "// Auto-generated by scripts/gen-commands.ts — do not edit manually",
  ...commands.map((name) => `import "#/commands/${name}.js";`),
  "",
].join("\n");

await Bun.write(`${import.meta.dir}/../src/commands/_all.ts`, content);
